### ISSUE TITLE
CQ-week

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/Parser#14]
- [x] Use cache for shop rules
- [x] Skip crawled pages of blacklisted shops.

**Comment by deeps96** [comment]
Use multiple Threads (Async from Spring), thread pool and callbacks to have one parser component consume multiple messages at once.

Store URL!  IS ALREADY PRESENT AS ID

**Comment by deeps96** [comment]
Take a look at:

`Caused by: java.lang.IllegalArgumentException: json string can not be null or empty
May 25 19:16:37 BP2017N2WS03 Parser-1.0.0.jar[29971]:         at com.jayway.jsonpath.internal.Utils.notEmpty(Utils.java:386)
May 25 19:16:37 BP2017N2WS03 Parser-1.0.0.jar[29971]:         at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:36)
May 25 19:16:37 BP2017N2WS03 Parser-1.0.0.jar[29971]:         at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:599)
May 25 19:16:37 BP2017N2WS03 Parser-1.0.0.jar[29971]:         at de.hpi.parser.service.DataExtractor.extract(DataExtractor.java:61)
`

This causes the parser to keep stuck within a return message and get it again loop.

**Comment by deeps96** [comment]
Check that retry annotation is existing. Parser seems to die, if SRG returns 404 - Retry exists, but had a bug - its fixed now

**Comment by deeps96** [comment]
CQ-Week is over!
